version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "edc-postgresql"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-pno37q2379dg"
s3_prefix = "edc-postgresql"
region = "us-east-1"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
parameter_overrides = "ParentVPCStack=\"\" ParentClientStack=\"\" VpcId=\"vpc-dee24aa4\" SubnetIds=\"subnet-5bb92275,subnet-59e7cb13\" ParentKmsKeyStack=\"\" ParentZoneStack=\"\" ParentSSHBastionStack=\"\" ParentAlertStack=\"\" DBSnapshotIdentifier=\"\" DBAllocatedStorage=\"100\" DBInstanceClass=\"db.t2.micro\" DBName=\"postgres\" DBBackupRetentionPeriod=\"30\" DBMasterUsername=\"master\" DBMasterUserPassword=\"Pwd2Stupid\" DBMultiAZ=\"false\" SubDomainNameWithDot=\"postgres.\" PreferredBackupWindow=\"20:54-21:24\" PreferredMaintenanceWindow=\"sat:03:00-sat:03:30\" EngineVersion=\"11.2\" EnableIAMDatabaseAuthentication=\"false\""

